import {Component, OnDestroy, OnInit} from '@angular/core';
import {FormBuilder, FormGroup, Validators} from '@angular/forms';
import {Subject} from 'rxjs';
import {InitMailService} from '../../app/services/init-mail.service';
import {AutoGenParamsModel} from '../../app/models/auto-gen-params.model';
import {Router} from '@angular/router';

@Component({
  selector: 'app-init-mail',
  templateUrl: './init-mail.component.html',
  styleUrls: ['./init-mail.component.scss']
})
export class InitMailComponent implements OnInit, OnDestroy {

    form: FormGroup;


    private _unsubscribeAll: Subject<any>;

    constructor(
        private _formBuilder: FormBuilder,
        private initMailService: InitMailService,
        private router: Router
    )
    {
        this._unsubscribeAll = new Subject();
    }

    // -----------------------------------------------------------------------------------------------------
    // @ Lifecycle hooks
    // -----------------------------------------------------------------------------------------------------

    /**
     * On init
     */
    ngOnInit(): void
    {

        this.form = this._formBuilder.group({
            receptionDate :  [],
            idDirectory :  [],
            idEntry :  [],
            idReceivedDocument : ['', Validators.required],
            dateReceivedDocument  : [],
            subject  : ['', Validators.required],
            sender  : ['', Validators.required],
            attachments : [],
            observations : [],
            priorityDegree : []
        });

        this.initMailService.getAutoGeneratedParamsFromBackend()
            .subscribe(
            (autoGeneratedParams) => {
             this.form.controls['idEntry'].setValue(autoGeneratedParams.idEntry);
             this.form.controls['idDirectory'].setValue(autoGeneratedParams.idDirectory);
             this.form.controls['receptionDate'].setValue(autoGeneratedParams.receptionDate);
             this.form.controls['idEntry'].disable();
             this.form.controls['idDirectory'].disable();
             this.form.controls['receptionDate'].disable();
             console.log(this.form.value);
            },
            (error) => {
                console.log('Error ! : ' + error);
            }
        );
    }

    /**
     * On destroy
     */
    ngOnDestroy(): void
    {
        // Unsubscribe from all subscriptions
        this._unsubscribeAll.next();
        this._unsubscribeAll.complete();
    }

    validateArrivedMail(): void{

        console.log(' fom', this.form);
        // console.log(this.autoGenParams);
        this.initMailService.sendArrivedMailFormToBackend(this.form.value)
            .subscribe(
                () => {
                   this.router.navigate(['arrivedMail-sc']);
                },
                (error) => {
                    console.log('Error ! : ' + error);
                }
            );

    }
}
